### ISSUE TITLE
Chrome Marked https://workgraph.cf/ As Dangerous after visiting https://workgraph.cf/1

### ISSUE THREAD

**Issue by chupper100** [snvmk/workgraph#2]
![img](https://user-images.githubusercontent.com/76856403/153805703-a262fe56-5eab-4efb-8606-941398bb445c.png)

# Reproduce
1. Visit [workgraph.cf/1](https://workgraph.cf/1).

**Comment by snvmk** [comment]
Hm, u sure that you are visiting it with https:// protocol, and not plain http://?

**Comment by snvmk** [comment]
I dont see such issue on my mobile (bromite, chromium fork). I will try installing google chrome to reproduce this

**Comment by snvmk** [comment]
Mobile google chrome doesnt say that. When i will be on laptop, i will try installing chrome.

**Comment by snvmk** [comment]
I installed google chrome stable. I dont see such issue. May I ask for your OS and chrome version?

**Comment by chupper100** [comment]
OS: Ubuntu 21.10
Chrome: 98.0.4758.80 (Official Build) (64-bit)

**Comment by chupper100** [comment]
I visited this exact url https://workgraph.cf/1

**Comment by snvmk** [comment]
Does issue still appear?

**Comment by chupper100** [comment]
Yes!

**Comment by snvmk** [comment]
Maybe you have something specific enabled in settings? Because i have exactly same build as you, and it doesnt appear

**Comment by snvmk** [comment]
![изображение](https://user-images.githubusercontent.com/93476469/153841530-d8573d83-477e-496d-8d12-caf92e4c7bc3.png)

**Comment by chupper100** [comment]
I enabled **Enhanced protection**

**Comment by snvmk** [comment]
Hm, let me try this

**Comment by chupper100** [comment]
![Screenshot from 2022-02-14 16-57-01](https://user-images.githubusercontent.com/76856403/153841893-87a33c9b-f800-41b4-a8ff-a5d02da8d54e.png)

**Comment by snvmk** [comment]
Wow, when i enabled it, this appeared
![изображение](https://user-images.githubusercontent.com/93476469/153842133-773a5d71-6d80-43fc-877a-e012da020437.png)

**Comment by chupper100** [comment]
Yes, that's what i get.

**Comment by snvmk** [comment]
Hm, now there is no that message on transparency report site

**Comment by snvmk** [comment]
Eh, again there

**Comment by chupper100** [comment]
The problem is actually solved, there's no more warning when I visit https://workgraph.cf/.
